Public Class FSCollections
    Private m_strEventType As String = ""
    Private m_strCitationType As String = ""
    Private m_bIsBaptism As Boolean = False
    Private m_bIsBirth As Boolean = False
    Private m_bIsBirthBapt As Boolean = False
    Private m_bIsBurial As Boolean = False
    Private m_bIsCensus As Boolean = False
    Private m_bIsDeath As Boolean = False
    Private m_bIsFS As Boolean = False
    Private m_bIsMarriage As Boolean = False
    Private m_bIsWAdmission As Boolean = False
    Private m_bDual As Boolean = False
    Private m_bMultiple As Boolean = False
    Private m_bIsProbate As Boolean = False
    Private m_bIsWarServiceRecord As Boolean = False
    Private m_bNoEventField As Boolean = False
    Private m_strDateFieldName As String = ""
    Private m_strPlaceFieldName As String = ""
    Private m_strFieldsList As String = ""

    Public Function SetEventTypeForIncomingCitation(IncomingCitation As String) As Boolean
        Dim bSuccess As Boolean = False
        If IncomingCitation.Contains("Alabama") = True Then
            If IncomingCitation.Contains("Alabama Births and Christenings, 1881-1930") = True Then
                m_strCitationType = "Alabama Births and Christenings, 1881-1930"
                m_bIsBirthBapt = True
                m_bNoEventField = True
                m_strDateFieldName = "Birth Date"
                m_strPlaceFieldName = "Birthplace"
                m_strFieldsList = "Name;EventType;EventDate;MilitaryUnitNote"
            ElseIf IncomingCitation.Contains("Alabama Civil War Service Records of Confederate Soldiers, 1861-1865") = True Then
                m_strCitationType = "Alabama Civil War Service Records of Confederate Soldiers, 1861-1865"
                m_strEventType = "Military Service"
                m_bIsWarServiceRecord = True
                m_strDateFieldName = "Event Date"
            ElseIf IncomingCitation.Contains("Alabama Civil War Service Records of Union Soldiers, 1861-1865") = True Then
                m_strCitationType = "Alabama Civil War Service Records of Union Soldiers, 1861-1865"
                m_strEventType = "Military Service"
                m_bIsWarServiceRecord = True
            ElseIf IncomingCitation.Contains("Alabama County Marriages, 1809-1950") = True Then
            ElseIf IncomingCitation.Contains("Alabama County Marriages, 1818-1936") = True Then
            ElseIf IncomingCitation.Contains("Alabama Deaths and Burials, 1881-1952") = True Then
            ElseIf IncomingCitation.Contains("Alabama Deaths, 1908-1974") = True Then
            ElseIf IncomingCitation.Contains("Alabama Estate Files, 1830-1976") = True Then
            ElseIf IncomingCitation.Contains("Alabama Marriages, 1816-1957") = True Then
            ElseIf IncomingCitation.Contains("Alabama State Census, 1855") = True Then
                m_strCitationType = "Alabama State Census, 1855"
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Alabama State Census, 1866") = True Then
                m_strCitationType = "Alabama State Census, 1866"
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Alabama, Census of Confederate Veterans, 1907, 1921, 1927") = True Then
                m_strCitationType = "Alabama, Census of Confederate Veterans, 1907, 1921, 1927"
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Alabama, Mobile Magnolia Cemetery Interment Cards, 1836-1995") = True Then
            End If
        ElseIf IncomingCitation.Contains("Alaska") = True Then
            If IncomingCitation.Contains("Alaska, Vital Records, 1816-1959") = True Then
            End If
        ElseIf IncomingCitation.Contains("Argentina") = True Then
            If IncomingCitation.Contains("Argentina Baptisms, 1645-1930") = True Then
            ElseIf IncomingCitation.Contains("Argentina Marriages, 1722-1911") = True Then
            ElseIf IncomingCitation.Contains("Argentina, Buenos Aires, Catholic Church Records, 1635-1981") = True Then
            ElseIf IncomingCitation.Contains("Argentina, Capital Federal, Catholic Church Records, 1737-1977") = True Then
            ElseIf IncomingCitation.Contains("Argentina, Capital Federal, Census, 1855") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Argentina, Catamarca, Catholic Church Records, 1724-1971") = True Then
                'ElseIf IncomingCitation.Contains("Argentina, Chaco, Catholic Church Records, 1882-1955") = True Then
                'ElseIf IncomingCitation.Contains("Argentina, Chubut, Catholic Church Records, 1884-1974") = True Then
            ElseIf IncomingCitation.Contains("Argentina, Corrientes, Catholic Church Records, 1734-1977") = True Then
            ElseIf IncomingCitation.Contains("Argentina, Córdoba, Catholic Church Records, 1557-1974") = True Then
                'ElseIf IncomingCitation.Contains("Argentina, Córdoba, Miscellaneous Records, 1574-1925") = True Then
            ElseIf IncomingCitation.Contains("Argentina, Entre Ríos, Catholic Church Records, 1764-1983") = True Then
            ElseIf IncomingCitation.Contains("Argentina, Jujuy, Catholic Church Records, 1662-1975") = True Then
            ElseIf IncomingCitation.Contains("Argentina, La Pampa, Catholic Church Records, 1882-1976") = True Then
            ElseIf IncomingCitation.Contains("Argentina, La Rioja, Catholic Church Records, 1714-1970") = True Then
            ElseIf IncomingCitation.Contains("Argentina, Mendoza, Catholic Church Records, 1665-1975") = True Then
            ElseIf IncomingCitation.Contains("Argentina, Misiones, Catholic Church Records, 1874-1975") = True Then
            ElseIf IncomingCitation.Contains("Argentina, National Census, 1869") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Argentina, National Census, 1895") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
                'ElseIf IncomingCitation.Contains("Argentina, Neuquén, Catholic Church Records, 1883-1977") = True Then
                'ElseIf IncomingCitation.Contains("Argentina, Río Negro, Catholic Church Records, 1880-1977") = True Then
            ElseIf IncomingCitation.Contains("Argentina, Salta, Catholic Church Records, 1634-1972") = True Then
            ElseIf IncomingCitation.Contains("Argentina, San Juan, Catholic Church Records, 1655-1975") = True Then
                'ElseIf IncomingCitation.Contains("Argentina, Santa Cruz, Catholic Church Records, 1886-1964") = True Then
            ElseIf IncomingCitation.Contains("Argentina, Santa Fe, Catholic Church Records, 1634-1975") = True Then
            ElseIf IncomingCitation.Contains("Argentina, Santiago del Estero, Catholic Church Records, 1581-1961") = True Then
                'ElseIf IncomingCitation.Contains("Argentina, Tierra del Fuego, Catholic Church Records, 1894-1950") = True Then
            ElseIf IncomingCitation.Contains("Argentina, Tucumán, Catholic Church Records, 1727-1955") = True Then
            End If
        ElseIf IncomingCitation.Contains("Arizona") = True Then
            If IncomingCitation.Contains("Arizona Births and Christenings, 1909-1917") = True Then
            ElseIf IncomingCitation.Contains("Arizona Civil War Service Records of Confederate Soldiers, 1861-1865") = True Then
            ElseIf IncomingCitation.Contains("Arizona Deaths and Burials, 1910-1911; 1933-1994") = True Then
            ElseIf IncomingCitation.Contains("Arizona Deaths, 1870-1951") = True Then
            ElseIf IncomingCitation.Contains("Arizona Marriages, 1865-1949") = True Then
            ElseIf IncomingCitation.Contains("Arizona Obituary Index to Arizona Newspapers, 1993-1994") = True Then
            ElseIf IncomingCitation.Contains("Arizona, County Marriages, 1871-1964") = True Then
            ElseIf IncomingCitation.Contains("Arizona, Douglas, Arrival Manifests, 1906-1955") = True Then
                'ElseIf IncomingCitation.Contains("Arizona, Maricopa County Probate Records, 1870-1930") = True Then
            ElseIf IncomingCitation.Contains("Arizona, Maricopa, Mesa City Cemetery Records, 1885-1960") = True Then
            ElseIf IncomingCitation.Contains("Arizona, Payson, Obituaries, 1948-2008") = True Then
            End If
        ElseIf IncomingCitation.Contains("Arkansas") = True Then
            If IncomingCitation.Contains("Arkansas Births and Christenings, 1812-1965") = True Then
            ElseIf IncomingCitation.Contains("Arkansas Church Marriages, 1860-1976") = True Then
            ElseIf IncomingCitation.Contains("Arkansas Civil War Service Records of Confederate Soldiers, 1861-1865") = True Then
            ElseIf IncomingCitation.Contains("Arkansas Civil War Service Records of Union Soldiers, 1861-1865") = True Then
                'ElseIf IncomingCitation.Contains("Arkansas Confederate Pensions, 1901-1929") = True Then
            ElseIf IncomingCitation.Contains("Arkansas Death Index, 1914-1950") = True Then
            ElseIf IncomingCitation.Contains("Arkansas Deaths and Burials, 1882-1929; 1945-1963") = True Then
            ElseIf IncomingCitation.Contains("Arkansas Divorce Index, 1923-1939") = True Then
            ElseIf IncomingCitation.Contains("Arkansas Ex-Confederate Pension Records, 1891-1939") = True Then
            ElseIf IncomingCitation.Contains("Arkansas First Draft Registration Cards, 1940-1945") = True Then
            ElseIf IncomingCitation.Contains("Arkansas Marriage Index, 1933-1939") = True Then
            ElseIf IncomingCitation.Contains("Arkansas Marriages, 1837-1944") = True Then
            ElseIf IncomingCitation.Contains("Arkansas Probate Records, 1817-1979") = True Then
            ElseIf IncomingCitation.Contains("Arkansas, County Marriages, 1837-1957") = True Then
            ElseIf IncomingCitation.Contains("Arkansas, Freedmen's Bureau Field Office Records, 1864-1872") = True Then
            ElseIf IncomingCitation.Contains("Arkansas, Oakland and Fraternal Historic Cemetery Records, 1867-2013") = True Then
            ElseIf IncomingCitation.Contains("Arkansas, Sebastian County Births and Deaths, 1877-1963") = True Then
            End If
        ElseIf IncomingCitation.Contains("Armenia Church Books, 1838-1929") = True Then
        ElseIf IncomingCitation.Contains("Australia") = True Then
            If IncomingCitation.Contains("Australia Births and Baptisms, 1792-1981") = True Then
            ElseIf IncomingCitation.Contains("Australia Cemetery Inscriptions, 1802-2005") = True Then
            ElseIf IncomingCitation.Contains("Australia Deaths and Burials, 1816-1980") = True Then
            ElseIf IncomingCitation.Contains("Australia Marriages, 1810-1980") = True Then
            ElseIf IncomingCitation.Contains("Australia Miscellaneous Genealogical Records, 1776-1980") = True Then
            ElseIf IncomingCitation.Contains("Australia, New South Wales, 1828 Census") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Australia, New South Wales, Alphabetical Index to Newspaper Cuttings, 1841-1987") = True Then
            ElseIf IncomingCitation.Contains("Australia, New South Wales, Cemetery, Military, and Church Record Transcripts, 1816-1982") = True Then
            ElseIf IncomingCitation.Contains("Australia, New South Wales, Census (fragment), 1841") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Australia, New South Wales, Census, 1891") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Australia, New South Wales, Deceased Estate Files, 1880-1923") = True Then
            ElseIf IncomingCitation.Contains("Australia, New South Wales, Index to Bounty Immigrants, 1828-1842") = True Then
            ElseIf IncomingCitation.Contains("Australia, Queensland Cemetery Records, 1802-1990") = True Then
            ElseIf IncomingCitation.Contains("Australia, Queensland, Immigration indexes, 1864-1940") = True Then
            ElseIf IncomingCitation.Contains("Australia, Queensland, Maryborough Public Records, 1847-1989") = True Then
            ElseIf IncomingCitation.Contains("Australia, Sydney Branch Genealogical Library, Cemetery Inscriptions, 1800-1960") = True Then
            ElseIf IncomingCitation.Contains("Australia, Tasmania, Civil Registration (District Registers), 1839-1938") = True Then
            ElseIf IncomingCitation.Contains("Australia, Tasmania, Civil Registration of Births, 1899-1912") = True Then
            ElseIf IncomingCitation.Contains("Australia, Tasmania, Civil Registration, 1803-1933") = True Then
            ElseIf IncomingCitation.Contains("Australia, Tasmania, Correspondence of the Immigration Office Concerning the Nomination, Arrival and Settlement of Migrants, 1920-1943") = True Then
            ElseIf IncomingCitation.Contains("Australia, Tasmania, Government Gazette, 1833-1925") = True Then
            ElseIf IncomingCitation.Contains("Australia, Tasmania, Migrant Files, 1945-1968") = True Then
            ElseIf IncomingCitation.Contains("Australia, Tasmania, Miscellaneous Records, 1829-2001") = True Then
            ElseIf IncomingCitation.Contains("Australia, Victoria Coastal Passenger Lists, 1852-1924") = True Then
            ElseIf IncomingCitation.Contains("Australia, Victoria, Assisted Immigrant Arrivals at Victorian Ports, 1839-1871") = True Then
            ElseIf IncomingCitation.Contains("Australia, Victoria, Index to Probate Registers, 1841-1989") = True Then
            ElseIf IncomingCitation.Contains("Australia, Victoria, Inquest Deposition Files, 1840-1925") = True Then
            ElseIf IncomingCitation.Contains("Australia, Victoria, Outward Passenger Lists, 1852-1924") = True Then
            End If
        ElseIf IncomingCitation.Contains("Austria") = True Then
            If IncomingCitation.Contains("Austria Births and Baptisms, 1651-1940") = True Then
            ElseIf IncomingCitation.Contains("Austria Burials, 1768-1918") = True Then
            ElseIf IncomingCitation.Contains("Austria Evangelical-Lutheran Church Records, 1848-1900") = True Then
            ElseIf IncomingCitation.Contains("Austria Marriages, 1722-1898") = True Then
            ElseIf IncomingCitation.Contains("Austria Seigniorial Records, 1537-1920") = True Then
            ElseIf IncomingCitation.Contains("Austria, Carinthia, Military Personnel Records, 1846-1897") = True Then
            ElseIf IncomingCitation.Contains("Austria, Tirol, Innsbruck, Sankt Jakob Parish Register Index, 1578-1970") = True Then
            ElseIf IncomingCitation.Contains("Austria, Upper Austria, Catholic Church Records, 1581-1919") = True Then
            ElseIf IncomingCitation.Contains("Austria, Upper Austria, Linz Citizen Rolls, 1658-1937") = True Then
            ElseIf IncomingCitation.Contains("Austria, Upper Austria, Linz, Death Certificates, 1818-1899") = True Then
            ElseIf IncomingCitation.Contains("Austria, Upper Austria, Linz, Miscellaneous City Records, 1485-1894") = True Then
            ElseIf IncomingCitation.Contains("Austria, Upper Austria, Wels, Census Records, 1613-1900") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Austria, Vienna Population Cards, 1850-1896") = True Then
            ElseIf IncomingCitation.Contains("Austria, Vienna, Jewish Registers of Births, Marriages, and Deaths, 1784-1911") = True Then
            End If
        ElseIf IncomingCitation.Contains("Bahamas") = True Then
            If IncomingCitation.Contains("Bahamas Births, 1850-1891") = True Then
            ElseIf IncomingCitation.Contains("Bahamas Civil Registration, 1850-1959") = True Then
            End If
        ElseIf IncomingCitation.Contains("Barbados") = True Then
            If IncomingCitation.Contains("Barbados Baptisms, 1739-1891") = True Then
            ElseIf IncomingCitation.Contains("Barbados Burials, 1854-1885") = True Then
            ElseIf IncomingCitation.Contains("Barbados Church Records, 1637-1887") = True Then
            ElseIf IncomingCitation.Contains("Barbados Marriages, 1854-1879") = True Then
            End If
        ElseIf IncomingCitation.Contains("Belgium") = True Then
            If IncomingCitation.Contains("Belgium Births and Baptisms, 1560-1890") = True Then
            ElseIf IncomingCitation.Contains("Belgium Deaths and Burials, 1564-1900") = True Then
            ElseIf IncomingCitation.Contains("Belgium Marriages, 1563-1890") = True Then
            ElseIf IncomingCitation.Contains("Belgium, Antwerp Police Immigration Index, 1840-1930") = True Then
            ElseIf IncomingCitation.Contains("Belgium, Antwerp, Civil Registration, 1588-1913") = True Then
            ElseIf IncomingCitation.Contains("Belgium, Antwerp, Police Immigration, 1840-1930") = True Then
            ElseIf IncomingCitation.Contains("Belgium, Brabant, Civil Registration, 1582-1914") = True Then
            ElseIf IncomingCitation.Contains("Belgium, East Flanders, Civil Registration, 1541-1914") = True Then
            ElseIf IncomingCitation.Contains("Belgium, Hainaut, Civil Registration, 1600-1913") = True Then
            ElseIf IncomingCitation.Contains("Belgium, Limburg, Civil Registration, 1798-1906") = True Then
            ElseIf IncomingCitation.Contains("Belgium, Liège, Civil Registration, 1621-1914") = True Then
            ElseIf IncomingCitation.Contains("Belgium, Luxembourg, Civil Registration, 1580-1920") = True Then
            ElseIf IncomingCitation.Contains("Belgium, Namur, Civil Registration, 1800-1912") = True Then
            ElseIf IncomingCitation.Contains("Belgium, West Flanders, Civil Registration, 1582-1910") = True Then
            End If
        ElseIf IncomingCitation.Contains("Benin, Civil Registration of Deaths, 1891-2014") = True Then
        ElseIf IncomingCitation.Contains("BillionGraves Index") = True Then
        ElseIf IncomingCitation.Contains("Bolivia") = True Then
            If IncomingCitation.Contains("Bolivia Baptisms, 1560-1938") = True Then
            ElseIf IncomingCitation.Contains("Bolivia Catholic Church Records, 1566-1996") = True Then
            ElseIf IncomingCitation.Contains("Bolivia Deaths, 1750-1920") = True Then
            ElseIf IncomingCitation.Contains("Bolivia Marriages, 1630-1940") = True Then
            End If
        ElseIf IncomingCitation.Contains("Brazil") = True Then
            If IncomingCitation.Contains("Brazil Baptisms, 1688-1935") = True Then
            ElseIf IncomingCitation.Contains("Brazil Deaths, 1750-1890") = True Then
            ElseIf IncomingCitation.Contains("Brazil Marriages, 1730-1955") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Bahia, Passenger Lists, 1855-1964") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Bahía, Catholic Church Records, 1598-2007") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Ceará, Catholic Church Records, 1725-1971") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Maranhão, Catholic Church Records, 1673-1962") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Minas Gerais, Belo Horizonte, Cemetery Records, 1897-2012") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Minas Gerais, Catholic Church Records, 1706-1999") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Paraná, Catholic Church Records, 1704-2008") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Paraná, Civil Registration, 1852-1996") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Paraíba, Catholic Church Records, 1731-2013") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Paraíba, Civil Registration, 1879-2007") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Pará, Catholic Church Records, 1930-1976") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Pernambuco, Catholic Church Records, 1762-2002") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Pernambuco, Civil Registration, 1804-2014") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Piauí, Civil Registration, 1875-2013") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Rio Grande do Norte, Catholic Church Records, 1788-1967") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Rio Grande do Sul, Catholic Church Records, 1738-1952") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Rio Grande do Sul, Miscellaneous Records, 1748-1998") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Rio de Janeiro, Catholic Church Records, 1616-1980") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Rio de Janeiro, Civil Registration, 1829-2012") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Rio de Janeiro, Immigration Cards, 1900-1965") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Santa Catarina, Catholic Church Records, 1714-1977") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Santa Catarina, Civil Registration, 1850-1999") = True Then
            ElseIf IncomingCitation.Contains("Brazil, Sergipe, Catholic Church Records, 1785-1994") = True Then
            ElseIf IncomingCitation.Contains("Brazil, São Paulo, Catholic Church Records, 1640-2012") = True Then
            ElseIf IncomingCitation.Contains("Brazil, São Paulo, Immigrant Hostelry Records, 1882-1925") = True Then
            ElseIf IncomingCitation.Contains("Brazil, São Paulo, Immigration Cards, 1902-1980") = True Then
            ElseIf IncomingCitation.Contains("Brazil, São Paulo, Port of Santos, Passenger and Immigrant Lists, 1960-1982") = True Then
            ElseIf IncomingCitation.Contains("Brazil, São Paulo, São Paulo, Burial Records, 1858-1977") = True Then
            End If
        ElseIf IncomingCitation.Contains("British") = True Then
            If IncomingCitation.Contains("British Columbia") = True Then
            ElseIf IncomingCitation.Contains("British Columbia Birth Registrations, 1854-1903") = True Then
            ElseIf IncomingCitation.Contains("British Columbia Death Registrations, 1872-1986; 1992-1993") = True Then
            ElseIf IncomingCitation.Contains("British Columbia Estate Files, 1859-1949") = True Then
            ElseIf IncomingCitation.Contains("British Columbia Marriage Registrations, 1859-1932; 1937-1938") = True Then
            ElseIf IncomingCitation.Contains("British Columbia Naturalization Records, 1859-1926") = True Then
            ElseIf IncomingCitation.Contains("British Columbia Wills, 1861-1981") = True Then
            ElseIf IncomingCitation.Contains("British Columbia, Crown Land Grant Records, 1851-1874") = True Then
            ElseIf IncomingCitation.Contains("British Columbia, Crown Land Grants, 1869-1930") = True Then
            ElseIf IncomingCitation.Contains("British Columbia, Crown Land Pre-emption Registers, 1860-1971") = True Then
            ElseIf IncomingCitation.Contains("British Columbia, Dominion Land Branch Records, 1885-1949") = True Then
            ElseIf IncomingCitation.Contains("British Columbia, Victoria Times Birth, Marriage and Death Notices, 1901-1939") = True Then
            ElseIf IncomingCitation.Contains("British Newspaper Archives, Obituaries") = True Then
            End If
        ElseIf IncomingCitation.Contains("California") = True Then
            If IncomingCitation.Contains("California Birth Index, 1905-1995") = True Then
            ElseIf IncomingCitation.Contains("California Births and Christenings, 1812-1988") = True Then
            ElseIf IncomingCitation.Contains("California Cemetery Transcriptions, 1850-1960") = True Then
            ElseIf IncomingCitation.Contains("California County Marriages, 1843-1918") = True Then
            ElseIf IncomingCitation.Contains("California County Naturalizations, 1849-1949") = True Then
            ElseIf IncomingCitation.Contains("California Death Index, 1905-1939") = True Then
            ElseIf IncomingCitation.Contains("California Death Index, 1940-1997") = True Then
            ElseIf IncomingCitation.Contains("California Divorce Index, 1966-1984") = True Then
            ElseIf IncomingCitation.Contains("California Great Registers, 1866-1910") = True Then
            ElseIf IncomingCitation.Contains("California Immigration Registers of Japanese, Filipinos, and Hawaiians at San Francisco, 1928-1942") = True Then
            ElseIf IncomingCitation.Contains("California Marriage Index, 1960-1985") = True Then
            ElseIf IncomingCitation.Contains("California Marriages, 1850-1945") = True Then
            ElseIf IncomingCitation.Contains("California Probate Estate Files, 1833-1991") = True Then
            ElseIf IncomingCitation.Contains("California State Census, 1852") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("California, Airplane Passenger Lists from Honolulu, Hawaii, 1947-1948") = True Then
            ElseIf IncomingCitation.Contains("California, Chinese Partnerships and Departures from San Francisco, 1893-1943") = True Then
            ElseIf IncomingCitation.Contains("California, Collections of the California Genealogical Society, 1700-1942") = True Then
            ElseIf IncomingCitation.Contains("California, County Birth and Death Records, 1800-1994") = True Then
            ElseIf IncomingCitation.Contains("California, County Marriages, 1850-1952") = True Then
            ElseIf IncomingCitation.Contains("California, Fresno and Napa Counties, Obituaries, 1974-1997") = True Then
            ElseIf IncomingCitation.Contains("California, Los Angeles Passenger Lists, 1907-1948") = True Then
            ElseIf IncomingCitation.Contains("California, Napa and Butte Counties, Obituaries, 1866-1992") = True Then
            ElseIf IncomingCitation.Contains("California, Northern U.S. District Court Naturalization Index, 1852-1989") = True Then
            ElseIf IncomingCitation.Contains("California, Oakland, Alameda County, Newspaper Record Collection, 1985-2011") = True Then
            ElseIf IncomingCitation.Contains("California, San Diego Naturalization Index, 1868-1958") = True Then
            ElseIf IncomingCitation.Contains("California, San Diego Passenger Lists, 1904-1952") = True Then
            ElseIf IncomingCitation.Contains("California, San Diego, Airplane Passenger and Crew Lists, 1929-1954") = True Then
            ElseIf IncomingCitation.Contains("California, San Diego, Chinese Passenger and Crew Lists, 1905-1923") = True Then
            ElseIf IncomingCitation.Contains("California, San Francisco Airplane Arrival Card Index, 1936-1949") = True Then
            ElseIf IncomingCitation.Contains("California, San Francisco Area Funeral Home Records, 1835-1979") = True Then
            ElseIf IncomingCitation.Contains("California, San Francisco County Records, 1824-1997") = True Then
            ElseIf IncomingCitation.Contains("California, San Francisco Passenger Lists, 1893-1953") = True Then
            ElseIf IncomingCitation.Contains("California, San Francisco Passenger and Crew Lists of Vessels Arriving, 1954-1957") = True Then
            ElseIf IncomingCitation.Contains("California, San Francisco, Immigration Office Special Inquiry Records, 1910-1941") = True Then
            ElseIf IncomingCitation.Contains("California, San Francisco, Register of Chinese Immigrant Court Cases and Foreign Seamen Tax Cards, 1883-1924") = True Then
            ElseIf IncomingCitation.Contains("California, San Francisco, World War I Enemy Alien Registration Affidavits, 1918") = True Then
            ElseIf IncomingCitation.Contains("California, San Joaquin, County Public Library Obituary Index, 1850-1991") = True Then
            ElseIf IncomingCitation.Contains("California, San Mateo County Records, 1851-1991") = True Then
            ElseIf IncomingCitation.Contains("California, San Mateo County, Colma, Italian Cemetery Records, 1899-2011") = True Then
            ElseIf IncomingCitation.Contains("California, San Pedro, Immigration Office Special Inquiry Records, 1930-1936") = True Then
            ElseIf IncomingCitation.Contains("California, Southern District Court (Central) Naturalization Index, 1915-1976") = True Then
            End If
        ElseIf IncomingCitation.Contains("Canad") = True Then
            If IncomingCitation.Contains("Canada Births and Baptisms, 1661-1959") = True Then
            ElseIf IncomingCitation.Contains("Canada Census Mortality Schedules, 1871") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Canada Census, 1851") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Canada Census, 1871") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Canada Census, 1881") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Canada Census, 1891") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Canada Census, 1901") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Canada Census, 1906") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Canada Census, 1911") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Canada Census, 1916") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Canada Deaths and Burials, 1664-1955") = True Then
            ElseIf IncomingCitation.Contains("Canada Marriages, 1661-1949") = True Then
            ElseIf IncomingCitation.Contains("Canada Passenger Lists, 1881-1922") = True Then
            ElseIf IncomingCitation.Contains("Canada, Lower Canada Census, 1825") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Canada, Lower Canada Census, 1831") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Canada, Lower Canada Census, 1842") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Canada, Merchant Marine Agreements and Accounts of Crews, 1890-1920") = True Then
            ElseIf IncomingCitation.Contains("Canada, Royal Canadian Mounted Police obituary card index and notices, 1876-2007") = True Then
            ElseIf IncomingCitation.Contains("Canada, Upper Canada Census, 1842") = True Then
            ElseIf IncomingCitation.Contains("Canadian Headstones") = True Then
            End If
        ElseIf IncomingCitation.Contains("Cape Verde, Catholic Church Records, 1787-1957") = True Then
        ElseIf IncomingCitation.Contains("Caribbean") = True Then
            If IncomingCitation.Contains("Caribbean Births and Baptisms, 1590-1928") = True Then
            ElseIf IncomingCitation.Contains("Caribbean Deaths and Burials, 1790-1906") = True Then
            ElseIf IncomingCitation.Contains("Caribbean Marriages, 1591-1905") = True Then
            End If
        ElseIf IncomingCitation.Contains("Central America, Colonial Records, 1607-1902") = True Then
        ElseIf IncomingCitation.Contains("Channel Islands Births and Baptisms, 1820-1907") = True Then
        ElseIf IncomingCitation.Contains("Chile") = True Then
            If IncomingCitation.Contains("Chile Baptisms, 1585-1932") = True Then
            ElseIf IncomingCitation.Contains("Chile Civil Registration, 1885-1903") = True Then
            ElseIf IncomingCitation.Contains("Chile Deaths, 1700-1920") = True Then
            ElseIf IncomingCitation.Contains("Chile Marriages, 1579-1930") = True Then
            ElseIf IncomingCitation.Contains("Chile, Cemetery Records, 1821-2015") = True Then
            End If
        ElseIf IncomingCitation.Contains("China") = True Then
            If IncomingCitation.Contains("China Cemetery Records, 1820-1983") = True Then
            ElseIf IncomingCitation.Contains("China Collection of Genealogies, 1239-2014") = True Then
            ElseIf IncomingCitation.Contains("China, Imperial Examinations and Related Papers (Han Yu-shan Collection), 1646-1904") = True Then
            End If
        ElseIf IncomingCitation.Contains("Colombia") = True Then
            If IncomingCitation.Contains("Colombia Baptisms, 1630-1950") = True Then
            ElseIf IncomingCitation.Contains("Colombia Deaths, 1770-1930") = True Then
            ElseIf IncomingCitation.Contains("Colombia Marriages, 1750-1960") = True Then
            ElseIf IncomingCitation.Contains("Colombia, Catholic Church Records, 1576-2014") = True Then
            ElseIf IncomingCitation.Contains("Colombia, Military Records, 1809-1958") = True Then
            ElseIf IncomingCitation.Contains("Colombia, Valle del Cauca, Miscellaneous Records, 1549-1955") = True Then
            End If
        ElseIf IncomingCitation.Contains("Colorado") = True Then
            If IncomingCitation.Contains("Colorado Naturalization Records, 1876-1990") = True Then
            ElseIf IncomingCitation.Contains("Colorado State Census, 1885") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Colorado Statewide Divorce Index, 1900-1939") = True Then
            ElseIf IncomingCitation.Contains("Colorado Statewide Marriage Index, 1853-2006") = True Then
            ElseIf IncomingCitation.Contains("Colorado, County Marriages, 1864-1995") = True Then
            ElseIf IncomingCitation.Contains("Colorado, Denver County Probate Case Files, 1900-1925") = True Then
            End If
        ElseIf IncomingCitation.Contains("Connecticut") = True Then
            If IncomingCitation.Contains("Connecticut Births and Christenings, 1649-1906") = True Then
            ElseIf IncomingCitation.Contains("Connecticut Death Index, 1949-2001") = True Then
            ElseIf IncomingCitation.Contains("Connecticut Deaths and Burials, 1772-1934") = True Then
            ElseIf IncomingCitation.Contains("Connecticut Divorce Index, 1968-1997") = True Then
            ElseIf IncomingCitation.Contains("Connecticut Marriage Index, 1959-2001") = True Then
            ElseIf IncomingCitation.Contains("Connecticut Marriages, 1630-1997") = True Then
            ElseIf IncomingCitation.Contains("Connecticut Marriages, 1640-1939") = True Then
            ElseIf IncomingCitation.Contains("Connecticut, District Court Naturalization Indexes, 1851-1992") = True Then
            End If
        ElseIf IncomingCitation.Contains("Cook Islands, Civil Registration, 1846-1989") = True Then
        ElseIf IncomingCitation.Contains("Costa Rica") = True Then
            If IncomingCitation.Contains("Costa Rica Baptisms, 1700-1915") = True Then
            ElseIf IncomingCitation.Contains("Costa Rica Deaths, 1787-1900") = True Then
            ElseIf IncomingCitation.Contains("Costa Rica Marriages, 1750-1920") = True Then
            ElseIf IncomingCitation.Contains("Costa Rica, Catholic Church Records, 1595-1992") = True Then
            ElseIf IncomingCitation.Contains("Costa Rica, Civil Registration, 1823-1975") = True Then
            End If
        ElseIf IncomingCitation.Contains("Croatia") = True Then
            If IncomingCitation.Contains("Croatia, Church Books, 1516-1994") = True Then
            ElseIf IncomingCitation.Contains("Croatia, Delnice Deanery Catholic Church Books, 1725-1926") = True Then
            End If
        ElseIf IncomingCitation.Contains("Currentobituary.com index, 2001-2014") = True Then
        ElseIf IncomingCitation.Contains("Czech") = True Then
            If IncomingCitation.Contains("Czech Republic Births and Baptisms, 1637-1889") = True Then
            ElseIf IncomingCitation.Contains("Czech Republic Censuses and Inhabitant Registers, 1800-1990") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Czech Republic Church Books, 1552-1963") = True Then
            ElseIf IncomingCitation.Contains("Czech Republic Civil Registers, 1874-1937") = True Then
            ElseIf IncomingCitation.Contains("Czech Republic Land Records, 1450-1889") = True Then
            ElseIf IncomingCitation.Contains("Czech Republic Marriages, 1654-1889") = True Then
            ElseIf IncomingCitation.Contains("Czech Republic, Archive of Trebon, Nobility Seignorial Records, 1579-1859") = True Then
            ElseIf IncomingCitation.Contains("Czech Republic, Northern Moravia, Opava Archive Church Books, 1571-1905") = True Then
            ElseIf IncomingCitation.Contains("Czech Republic, School Registers, 1799-1953") = True Then
            ElseIf IncomingCitation.Contains("Czech Republic, Southern Bohemia, Trebon Archive Church Books, 1650-1900") = True Then
            End If
        ElseIf IncomingCitation.Contains("Dakota Territory Civil War Service Records of Union Soldiers, 1861-1865") = True Then
        ElseIf IncomingCitation.Contains("Delaware") = True Then
            If IncomingCitation.Contains("Delaware Baptisms, 1697-1886") = True Then
            ElseIf IncomingCitation.Contains("Delaware Births and Christenings, 1710-1896") = True Then
            ElseIf IncomingCitation.Contains("Delaware Church Deaths, 1750-1886") = True Then
            ElseIf IncomingCitation.Contains("Delaware Civil War Service Records of Union Soldiers, 1861-1865") = True Then
            ElseIf IncomingCitation.Contains("Delaware Death Records, 1855-1961") = True Then
            ElseIf IncomingCitation.Contains("Delaware Deaths and Burials, 1815-1955") = True Then
            ElseIf IncomingCitation.Contains("Delaware Marriage Records, 1913-1954") = True Then
            ElseIf IncomingCitation.Contains("Delaware Marriages and Marriage Licenses, 1683-1894") = True Then
            ElseIf IncomingCitation.Contains("Delaware Marriages, 1713-1919") = True Then
            ElseIf IncomingCitation.Contains("Delaware Orphan Court Records, 1680-1978") = True Then
            ElseIf IncomingCitation.Contains("Delaware State Birth Records, 1861-1922") = True Then
            ElseIf IncomingCitation.Contains("Delaware Vital Record Index Cards, 1680-1934") = True Then
            ElseIf IncomingCitation.Contains("Delaware Vital Records, 1650-1974") = True Then
            ElseIf IncomingCitation.Contains("Delaware, County Naturalization Records, 1796-1958") = True Then
            ElseIf IncomingCitation.Contains("Delaware, Wilmington Vital Records, 1847-1954") = True Then
            End If
        ElseIf IncomingCitation.Contains("Denmark") = True Then
            If IncomingCitation.Contains("Denmark Baptisms, 1618-1923") = True Then
            ElseIf IncomingCitation.Contains("Denmark Burials, 1640-1917") = True Then
            ElseIf IncomingCitation.Contains("Denmark Census, 1911") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Denmark Census, 1916") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Denmark Census, 1925") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Denmark Church Records, 1484-1941") = True Then
            ElseIf IncomingCitation.Contains("Denmark Civil Marriages, 1851-1961") = True Then
            ElseIf IncomingCitation.Contains("Denmark Deeds and Mortgages, 1572-1928") = True Then
            ElseIf IncomingCitation.Contains("Denmark Estate Records, 1436-1964") = True Then
            ElseIf IncomingCitation.Contains("Denmark Marriages, 1635-1916") = True Then
            ElseIf IncomingCitation.Contains("Denmark, Copenhagen City, Civil Marriages, 1739-1964, Index 1877-1964") = True Then
            ElseIf IncomingCitation.Contains("Denmark, Military Conscription Rolls, 1789-1792") = True Then
            ElseIf IncomingCitation.Contains("Denmark, Probate Indexes, 1674-1851") = True Then
            End If
        ElseIf IncomingCitation.Contains("District of Columbia") = True Then
            If IncomingCitation.Contains("District of Columbia Birth Returns, 1874-1897") = True Then
            ElseIf IncomingCitation.Contains("District of Columbia Births and Christenings, 1830-1955") = True Then
            ElseIf IncomingCitation.Contains("District of Columbia Court and Emancipation Records, 1820-1863") = True Then
            ElseIf IncomingCitation.Contains("District of Columbia Deaths and Burials, 1840-1964") = True Then
            ElseIf IncomingCitation.Contains("District of Columbia Deaths, 1874-1961") = True Then
            ElseIf IncomingCitation.Contains("District of Columbia Marriages, 1811-1950") = True Then
            ElseIf IncomingCitation.Contains("District of Columbia Marriages, 1830-1921") = True Then
            ElseIf IncomingCitation.Contains("District of Columbia, Freedmen's Bureau Field Office Records, 1863-1872") = True Then
            ElseIf IncomingCitation.Contains("District of Columbia, Glenwood Cemetery Records, 1854-2013") = True Then
            End If
        ElseIf IncomingCitation.Contains("Dominican Republic") = True Then
            If IncomingCitation.Contains("Dominican Republic Baptisms, 1726-1924") = True Then
            ElseIf IncomingCitation.Contains("Dominican Republic Births, 1801-2006") = True Then
            ElseIf IncomingCitation.Contains("Dominican Republic Civil Registration, 1801-2010") = True Then
            ElseIf IncomingCitation.Contains("Dominican Republic Deaths, 1666-1862") = True Then
            ElseIf IncomingCitation.Contains("Dominican Republic Marriages, 1743-1929") = True Then
            ElseIf IncomingCitation.Contains("Dominican Republic Miscellaneous Records, 1921-1980") = True Then
            ElseIf IncomingCitation.Contains("Dominican Republic, Catholic Church Records, 1590-1955") = True Then
            End If
        ElseIf IncomingCitation.Contains("Ecuador") = True Then
            If IncomingCitation.Contains("Ecuador Baptisms, 1680-1930") = True Then
            ElseIf IncomingCitation.Contains("Ecuador Deaths, 1800-1920") = True Then
            ElseIf IncomingCitation.Contains("Ecuador Marriages, 1680-1930") = True Then
            ElseIf IncomingCitation.Contains("Ecuador, Catholic Church Records, 1565-2011") = True Then
            End If
        ElseIf IncomingCitation.Contains("El Salvador") = True Then
            If IncomingCitation.Contains("El Salvador Baptisms, 1750-1940") = True Then
            ElseIf IncomingCitation.Contains("El Salvador Catholic Church Records, 1655-1977") = True Then
            ElseIf IncomingCitation.Contains("El Salvador Civil Registration, 1704-1990") = True Then
            ElseIf IncomingCitation.Contains("El Salvador Marriages, 1810-1930 ") = True Then
            End If
        ElseIf IncomingCitation.Contains("England") = True Then
            If IncomingCitation.Contains("Census") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
                If IncomingCitation.Contains("England and Wales Census, 1841") = True Then
                ElseIf IncomingCitation.Contains("England and Wales Census, 1851") = True Then
                ElseIf IncomingCitation.Contains("England and Wales Census, 1861") = True Then
                ElseIf IncomingCitation.Contains("England and Wales Census, 1871") = True Then
                ElseIf IncomingCitation.Contains("England and Wales Census, 1881") = True Then
                ElseIf IncomingCitation.Contains("England and Wales Census, 1891") = True Then
                ElseIf IncomingCitation.Contains("England and Wales Census, 1901") = True Then
                ElseIf IncomingCitation.Contains("England and Wales Census, 1911") = True Then
                End If
            ElseIf IncomingCitation.Contains("Cheshire") = True Then
                If IncomingCitation.Contains("England, Cheshire Bishop's Transcripts, 1598-1900") = True Then
                ElseIf IncomingCitation.Contains("England, Cheshire Non-conformist Records, 1671-1900") = True Then
                ElseIf IncomingCitation.Contains("England, Cheshire Parish Registers, 1538-2000") = True Then
                ElseIf IncomingCitation.Contains("England, Cheshire Probate Records, 1492-1940") = True Then
                ElseIf IncomingCitation.Contains("England, Cheshire Workhouse Records, 1848-1967") = True Then
                ElseIf IncomingCitation.Contains("England, Cheshire, Land Tax Assessments, 1778-1832") = True Then
                ElseIf IncomingCitation.Contains("England, Cheshire, Marriage Bonds and Allegations, 1606-1900") = True Then
                ElseIf IncomingCitation.Contains("England, Cheshire, Register of Electors, 1842-1900") = True Then
                ElseIf IncomingCitation.Contains("England, Cheshire, School Records, 1796-1950") = True Then
                End If
            ElseIf IncomingCitation.Contains("England Births and Christenings, 1538-1975") = True Then
            ElseIf IncomingCitation.Contains("England Deaths and Burials, 1538-1991") = True Then
            ElseIf IncomingCitation.Contains("England Marriages, 1538–1973") = True Then
            ElseIf IncomingCitation.Contains("England and Wales Birth Registration Index, 1837-2008") = True Then
            ElseIf IncomingCitation.Contains("England and Wales Death Registration Index 1837-2007") = True Then
            ElseIf IncomingCitation.Contains("England and Wales Marriage Registration Index, 1837-2005") = True Then
            ElseIf IncomingCitation.Contains("England and Wales Non-Conformist Record Indexes (RG4-8), 1588-1977") = True Then
            ElseIf IncomingCitation.Contains("England, Bristol Parish Registers, 1538-1900") = True Then
            ElseIf IncomingCitation.Contains("England, Bristol, Non-Conformist Church Records, 1777-1936") = True Then
            ElseIf IncomingCitation.Contains("England, Cambridgeshire Bishop's Transcripts, 1599-1860") = True Then
            ElseIf IncomingCitation.Contains("England, Cornwall Parish Registers, 1538-2010") = True Then
            ElseIf IncomingCitation.Contains("England, Derbyshire, Church of England Parish Registers, 1537-1918") = True Then
            ElseIf IncomingCitation.Contains("England, Devon Bishop's Transcripts, 1558-1887") = True Then
            ElseIf IncomingCitation.Contains("England, Devon and Cornwall Marriages, 1660-1912") = True Then
            ElseIf IncomingCitation.Contains("England, Devon, Parish Registers, 1538-1912") = True Then
            ElseIf IncomingCitation.Contains("England, Dorset, Parish Registers, 1538-1936") = True Then
            ElseIf IncomingCitation.Contains("England, Durham Diocese Bishop's Transcripts, 1639-1919") = True Then
            ElseIf IncomingCitation.Contains("England, Durham Diocese, Allertonshire Peculiar Administration Bonds and Inventories, 1670-1808") = True Then
            ElseIf IncomingCitation.Contains("England, Durham Diocese, Allertonshire Peculiar Stray Probate Bonds, 1732-1768") = True Then
            ElseIf IncomingCitation.Contains("England, Durham Diocese, Calendar of Marriage Bonds & Allegations, 1594-1815") = True Then
            ElseIf IncomingCitation.Contains("England, Durham Diocese, Marriage Bonds & Allegations, 1692-1900") = True Then
            ElseIf IncomingCitation.Contains("England, Durham Diocese, Original Will Strays, 1743-1900") = True Then
            ElseIf IncomingCitation.Contains("England, Durham Diocese, Probate Inventories, 1676-1846") = True Then
            ElseIf IncomingCitation.Contains("England, Durham Diocese, Registered Wills 1526-1858") = True Then
            ElseIf IncomingCitation.Contains("England, Durham Diocese, Renunciations, 1767 and 1794") = True Then
            ElseIf IncomingCitation.Contains("England, Durham Probate Bonds, 1556-1858") = True Then
            ElseIf IncomingCitation.Contains("England, Durham Probate Commissions, Monitions and Citations, 1650-1858") = True Then
            ElseIf IncomingCitation.Contains("England, Durham, Dean and Chapter of Durham's Allerton and Allertonshire Original Wills, Inventories and Bonds, 1666-1845") = True Then
            ElseIf IncomingCitation.Contains("England, Durham, Diocese of Durham Original Wills, 1650-1857") = True Then
            ElseIf IncomingCitation.Contains("England, Essex Parish Registers, 1538-1997") = True Then
            ElseIf IncomingCitation.Contains("England, Essex, Bishop's Transcripts, 1779-1892") = True Then
            ElseIf IncomingCitation.Contains("England, Kent, Bishop's Transcripts, 1560-1911") = True Then
            ElseIf IncomingCitation.Contains("England, Kent, Land Tax Assessments, 1689-1832") = True Then
            ElseIf IncomingCitation.Contains("England, Kent, Manorial Documents, 1241-1976") = True Then
            ElseIf IncomingCitation.Contains("England, Kent, Parish Registers, 1538-1911") = True Then
            ElseIf IncomingCitation.Contains("England, Kent, Quarter Sessions and Court Files, 1558-1899") = True Then
            ElseIf IncomingCitation.Contains("England, Kent, Register of Electors, 1570-1907") = True Then
            ElseIf IncomingCitation.Contains("England, Kent, Wills and Probate, 1440-1881") = True Then
            ElseIf IncomingCitation.Contains("England, Kent, Workhouse Records, 1777-1911") = True Then
            ElseIf IncomingCitation.Contains("England, Lancashire, Oldham Cemetery Registers, 1797-2004") = True Then
            ElseIf IncomingCitation.Contains("England, Lancashire, Parish Registers 1538-1910") = True Then
            ElseIf IncomingCitation.Contains("England, London Electoral Registers, 1847-1913") = True Then
            ElseIf IncomingCitation.Contains("England, Manchester, Miscellaneous Records, 1700-1916") = True Then
            ElseIf IncomingCitation.Contains("England, Manchester, Parish Registers, 1603-1910") = True Then
            ElseIf IncomingCitation.Contains("England, Middlesex, Westminster, Parish Registers, 1538-1912") = True Then
            ElseIf IncomingCitation.Contains("England, Norfolk Archdeacon's Transcripts, 1600-1812") = True Then
            ElseIf IncomingCitation.Contains("England, Norfolk Bishop's Transcripts, 1685-1941") = True Then
            ElseIf IncomingCitation.Contains("England, Norfolk Marriage Bonds, 1557-1915") = True Then
            ElseIf IncomingCitation.Contains("England, Norfolk Monumental Inscriptions, 1600-1900's") = True Then
            ElseIf IncomingCitation.Contains("England, Norfolk Non-conformist Records, 1613-1901") = True Then
            ElseIf IncomingCitation.Contains("England, Norfolk Poor Law Union Records, 1796-1900") = True Then
            ElseIf IncomingCitation.Contains("England, Norfolk Register of Electors, 1832-1915") = True Then
            ElseIf IncomingCitation.Contains("England, Norfolk, Parish Registers (County Record Office), 1510-1997") = True Then
            ElseIf IncomingCitation.Contains("England, Northumberland, Cumberland, Durham, Miscellaneous Records, 969-2007") = True Then
            ElseIf IncomingCitation.Contains("England, Northumberland, Non-conformist Records, 1708-1982") = True Then
            ElseIf IncomingCitation.Contains("England, Northumberland, Parish Registers, 1538-1950") = True Then
            ElseIf IncomingCitation.Contains("England, Staffordshire, Church Records, 1538-1944") = True Then
            ElseIf IncomingCitation.Contains("England, Sussex, Parish Registers, 1538-1910") = True Then
            ElseIf IncomingCitation.Contains("England, Warwickshire, Parish Registers, 1535-1984") = True Then
            ElseIf IncomingCitation.Contains("England, Westminster Rate Books, 1634-1900") = True Then
            ElseIf IncomingCitation.Contains("England, Yorkshire, Allertonshire, Marriage Bonds & Allegations, 1667-1819") = True Then
            End If
        ElseIf IncomingCitation.Contains("Estonia") = True Then
            If IncomingCitation.Contains("Estonia Church Books and Synagogue Registers, 1835-1940") = True Then
            ElseIf IncomingCitation.Contains("Estonia Population Registers, 1918-1944") = True Then
            ElseIf IncomingCitation.Contains("Estonia, Petseri County, Surname Register Cards, 1921-1923") = True Then
            End If
        ElseIf IncomingCitation.Contains("Family Group Records Collection, Archives Section, 1942-1969") = True Then
        ElseIf IncomingCitation.Contains("Find A Grave Index") = True Then
        ElseIf IncomingCitation.Contains("Finland") = True Then
            If IncomingCitation.Contains("Finland Baptisms, 1657-1890") = True Then
            ElseIf IncomingCitation.Contains("Finland Burials, 1725-1909") = True Then
            ElseIf IncomingCitation.Contains("Finland Marriages, 1682-1892") = True Then
            ElseIf IncomingCitation.Contains("Finland, Turku-Pori, Church Records, 1667-1900") = True Then
            End If
        ElseIf IncomingCitation.Contains("Florida") = True Then
            If IncomingCitation.Contains("Florida Births and Christenings, 1880-1935") = True Then
            ElseIf IncomingCitation.Contains("Florida Civil War Service Records of Confederate Soldiers, 1861-1865") = True Then
            ElseIf IncomingCitation.Contains("Florida Civil War Service Records of Union Soldiers, 1861-1865") = True Then
            ElseIf IncomingCitation.Contains("Florida Confederate Veterans and Widows Pension Applications, 1885-1955") = True Then
            ElseIf IncomingCitation.Contains("Florida Death Index, 1877-1998") = True Then
            ElseIf IncomingCitation.Contains("Florida Deaths and Burials, 1900-1921") = True Then
            ElseIf IncomingCitation.Contains("Florida Deaths, 1877-1939") = True Then
            ElseIf IncomingCitation.Contains("Florida Divorce Index, 1927-2001") = True Then
            ElseIf IncomingCitation.Contains("Florida Marriage Index, 1822-1875 and 1927-2001") = True Then
            ElseIf IncomingCitation.Contains("Florida Marriages, 1830-1993") = True Then
            ElseIf IncomingCitation.Contains("Florida Marriages, 1837-1974") = True Then
            ElseIf IncomingCitation.Contains("Florida Probate Records, 1784-1990") = True Then
            ElseIf IncomingCitation.Contains("Florida State Census, 1885") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Florida State Census, 1935") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Florida State Census, 1945") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Florida and South Carolina, Airplane Arrival Manifests, 1944-1945") = True Then
            ElseIf IncomingCitation.Contains("Florida, County Marriages, 1830-1957") = True Then
            ElseIf IncomingCitation.Contains("Florida, Fort Lauderdale Crew Lists, 1939-1945") = True Then
            ElseIf IncomingCitation.Contains("Florida, Key West Passenger Lists, 1898-1945") = True Then
            ElseIf IncomingCitation.Contains("Florida, Knights Keys Passenger Lists, 1908-1912") = True Then
            ElseIf IncomingCitation.Contains("Florida, Old Confederate Soldiers and Sailors Home records, 1888-1938") = True Then
            ElseIf IncomingCitation.Contains("Florida, Pensacola, Passenger Lists, 1900-1945") = True Then
            ElseIf IncomingCitation.Contains("Florida, Port Everglades Passenger Lists, 1932-1951") = True Then
            ElseIf IncomingCitation.Contains("Florida, Spanish Land Grants, 1763-1821") = True Then
            ElseIf IncomingCitation.Contains("Florida, Tampa, Passenger Lists, 1898-1945") = True Then
            ElseIf IncomingCitation.Contains("Florida, World War I Service Cards, 1917-1919") = True Then
            End If
        ElseIf IncomingCitation.Contains("France") = True Then
            If IncomingCitation.Contains("France, Auvergne, Family Genealogies by Colonel Etienne de Bellaigue de Bughas, 1400-1900") = True Then
            ElseIf IncomingCitation.Contains("France, Coutances et d'Avranche Diocese, Catholic Parish Records, 1533-1894") = True Then
            ElseIf IncomingCitation.Contains("France, Coutances et d'Avranche Diocese, Inquiries of Consanguinity, 1597-1818") = True Then
            ElseIf IncomingCitation.Contains("France, Côtes-d'Armor, Census, 1876") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("France, Côtes-d'Armor, Census, 1891") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("France, Côtes-d'Armor, Census, 1906") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("France, Dordogne, Censuses, 1856") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("France, Dordogne, Censuses, 1876") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("France, Finistère, Quimper et Léon Diocese, Catholic Parish Records, 1772-1894") = True Then
            ElseIf IncomingCitation.Contains("France, Haute-Garonne, Toulouse, Censuses, 1830-1831") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("France, Haute-Garonne, Toulouse, Censuses, 1872 and 1886") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("France, Haute-Garonne, Toulouse, Censuses, 1891") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("France, Haute-Garonne, Toulouse, Church Records, 1539-1793") = True Then
            ElseIf IncomingCitation.Contains("France, Haute-Garonne, Toulouse, Civil Registration, 1792-1893") = True Then
            ElseIf IncomingCitation.Contains("France, Hérault, Census, 1876") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("France, Hérault, Census, 1891") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("France, Hérault, Census, 1906") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("France, Nord, Census, 1906") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("France, Protestant Church Records, 1536-1894") = True Then
            ElseIf IncomingCitation.Contains("France, Saône-et-Loire, Census, 1876") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("France, Saône-et-Loire, Military Conscriptions, 1867-1940") = True Then
            ElseIf IncomingCitation.Contains("France, Seine-Maritime, Rouen, Indexes to Church Records, 1680-1789") = True Then
            End If
        ElseIf IncomingCitation.Contains("Georgia") = True Then
            If IncomingCitation.Contains("Georgia Births and Christenings, 1754-1960") = True Then
            ElseIf IncomingCitation.Contains("Georgia Church Marriages, 1754-1960") = True Then
            ElseIf IncomingCitation.Contains("Georgia Civil War Service Records of Confederate Soldiers, 1861-1865") = True Then
            ElseIf IncomingCitation.Contains("Georgia Civil War Service Records of Union Soldiers, 1861-1865") = True Then
            ElseIf IncomingCitation.Contains("Georgia Confederate Home Records, 1901-1930") = True Then
            ElseIf IncomingCitation.Contains("Georgia Death Index, 1933-1998") = True Then
            ElseIf IncomingCitation.Contains("Georgia Deaths, 1914-1927") = True Then
            ElseIf IncomingCitation.Contains("Georgia Deaths, 1928-1940") = True Then
            ElseIf IncomingCitation.Contains("Georgia Marriages, 1808-1967") = True Then
            ElseIf IncomingCitation.Contains("Georgia Probate Records, 1742-1990") = True Then
            ElseIf IncomingCitation.Contains("Georgia World War II Draft Registration Cards, 1940-1945") = True Then
            ElseIf IncomingCitation.Contains("Georgia, Andersonville Prison Records, 1862-1865") = True Then
            ElseIf IncomingCitation.Contains("Georgia, Brunswick Passenger Lists, 1904-1939") = True Then
            ElseIf IncomingCitation.Contains("Georgia, Church Marriages, 1787-1962") = True Then
            ElseIf IncomingCitation.Contains("Georgia, County Marriages, 1785-1950") = True Then
            ElseIf IncomingCitation.Contains("Georgia, Elbert County Records, 1790-2002") = True Then
            ElseIf IncomingCitation.Contains("Georgia, Freedmen's Bureau Field Office Records, 1865-1872") = True Then
            ElseIf IncomingCitation.Contains("Georgia, Fulton County Records from the Atlanta History Center, 1827-1955") = True Then
            ElseIf IncomingCitation.Contains("Georgia, Hall County Marriages, 1950-2005") = True Then
            ElseIf IncomingCitation.Contains("Georgia, Headright and Bounty Land Records, 1783-1909") = True Then
            End If
        ElseIf IncomingCitation.Contains("Germany") = True Then
            If IncomingCitation.Contains("Germany Births and Baptisms, 1558-1898") = True Then
            ElseIf IncomingCitation.Contains("Germany Deaths and Burials, 1582-1958") = True Then
            ElseIf IncomingCitation.Contains("Germany Marriages, 1558-1929") = True Then
            ElseIf IncomingCitation.Contains("Germany, Anhalt, Dessau, City Directories, 1866-1919") = True Then
            ElseIf IncomingCitation.Contains("Germany, Anhalt, Köthen, Miscellaneous City Records, 1630-1921") = True Then
            ElseIf IncomingCitation.Contains("Germany, Baden, Church Book Duplicates, 1800-1870") = True Then
            ElseIf IncomingCitation.Contains("Germany, Baden, Stebbach, Church Book Extracts, 1675-1951") = True Then
            ElseIf IncomingCitation.Contains("Germany, Bavaria, Deggendorf, Miscellaneous City Records, 1600-1900") = True Then
            ElseIf IncomingCitation.Contains("Germany, Bavaria, Dinkelsbühl Miscellaneous City Records, 1804-1946") = True Then
            ElseIf IncomingCitation.Contains("Germany, Bavaria, Fürth, Emigration and City Directories, 1805-1913") = True Then
            ElseIf IncomingCitation.Contains("Germany, Bavaria, Mindelheim Miscellaneous City Records, 1407-1950") = True Then
            ElseIf IncomingCitation.Contains("Germany, Bavaria, Neuburg an der Donau Miscellaneous City Records, 1808-1949") = True Then
            ElseIf IncomingCitation.Contains("Germany, Bavaria, Neumarkt Miscellaneous City Records, 1453-1973") = True Then
            ElseIf IncomingCitation.Contains("Germany, Bavaria, Nuremberg Civil Registration, 1803-1886") = True Then
            ElseIf IncomingCitation.Contains("Germany, Bavaria, Nördlingen, Miscellaneous City Records, 1385-1943") = True Then
            ElseIf IncomingCitation.Contains("Germany, Bavaria, Passau, Miscellaneous City Records, 1700-1940") = True Then
            ElseIf IncomingCitation.Contains("Germany, Bavaria, Straubing, Miscellaneous City Records, 1765-1917") = True Then
            ElseIf IncomingCitation.Contains("Germany, Bavaria, Traunstein, Family Group Sheets, 1830-1900") = True Then
            ElseIf IncomingCitation.Contains("Germany, Bavaria, Traunstein, Military Records, 1830-1918") = True Then
            ElseIf IncomingCitation.Contains("Germany, Brandenburg, Berlin, Probate Records, 1796-1853") = True Then
            ElseIf IncomingCitation.Contains("Germany, Brandenburg, Bernau bei Berlin, Jewish Records, 1688-1872") = True Then
            ElseIf IncomingCitation.Contains("Germany, Brandenburg, Wittenberge, City Directories and Citizen Lists, 1851-1921") = True Then
            ElseIf IncomingCitation.Contains("Germany, Bremen Passenger Departure Lists, 1904-1914") = True Then
            ElseIf IncomingCitation.Contains("Germany, Hesse, Civil Registration, 1874-1927") = True Then
            ElseIf IncomingCitation.Contains("Germany, Hesse, Frankfurt, Civil Registration Deaths Indexes, 1928-1978") = True Then
            ElseIf IncomingCitation.Contains("Germany, Hesse, Frankfurt, Civil Registration, 1811-1814, 1833-1928") = True Then
            ElseIf IncomingCitation.Contains("Germany, Hesse-Nassau, Civil Registers and Church Books, 1701-1875") = True Then
            ElseIf IncomingCitation.Contains("Germany, Hessen, Darmstadt City Records, 1627-1940") = True Then
            ElseIf IncomingCitation.Contains("Germany, Mecklenburg-Schwerin Census, 1867") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Germany, Mecklenburg-Schwerin Census, 1890") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Germany, Mecklenburg-Schwerin Census, 1900") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Germany, Prussia, Brandenburg and Posen, Church Book Duplicates, 1794-1874") = True Then
            ElseIf IncomingCitation.Contains("Germany, Prussia, Brandenburg, Angermünde, Miscellaneous City Records 1706-1922") = True Then
            ElseIf IncomingCitation.Contains("Germany, Prussia, Brandenburg, Cottbus, Miscellaneous City Records, 1672-1919") = True Then
            ElseIf IncomingCitation.Contains("Germany, Prussia, Brandenburg, Eberswalde, City Directories, 1890-1919") = True Then
            ElseIf IncomingCitation.Contains("Germany, Prussia, Brandenburg, Heegermühle, Church Records, 1664-1824") = True Then
            ElseIf IncomingCitation.Contains("Germany, Prussia, Brandenburg, Landkreis Ostprignitz-Ruppin, Miscellaneous Records, 1559-1945") = True Then
            ElseIf IncomingCitation.Contains("Germany, Prussia, East Prussia, Königsberg, Funeral Sermons, 1597-1794") = True Then
            ElseIf IncomingCitation.Contains("Germany, Prussia, East Prussia, Königsberg, Index to Funeral Sermons and Memorials, 1700-1900") = True Then
            ElseIf IncomingCitation.Contains("Germany, Prussia, Pomerania Church Records, 1544-1945") = True Then
            ElseIf IncomingCitation.Contains("Germany, Prussia, Pomerania, Labes, Church Records, 1647-1764") = True Then
            ElseIf IncomingCitation.Contains("Germany, Prussia, Pomerania, Stralsund, Church Book Indexes, 1600-1900") = True Then
            ElseIf IncomingCitation.Contains("Germany, Prussia, Saxony, Halle, Miscellaneous City Records, 1401-1926") = True Then
            ElseIf IncomingCitation.Contains("Germany, Prussia, Saxony, Nordhausen, City Directories, 1824-1919") = True Then
            ElseIf IncomingCitation.Contains("Germany, Prussia, Saxony, Various Protestant Church Records, 1594-1951") = True Then
            ElseIf IncomingCitation.Contains("Germany, Prussia, Westphalia, Minden, Miscellaneous Collections from the Municipal Archives, 1574-1912") = True Then
            ElseIf IncomingCitation.Contains("Germany, Rhineland-Palatinate Church Record Extractions and Family Registers, 1600-1925") = True Then
            ElseIf IncomingCitation.Contains("Germany, Sachsen-Weimar-Eisenach, Jena, City Directories, 1810-1935") = True Then
            ElseIf IncomingCitation.Contains("Germany, Saxe-Meiningen, Saalfeld an der Saale, Miscellaneous City Records, 1876-1920") = True Then
            ElseIf IncomingCitation.Contains("Germany, Saxony, Bautzen, Church Records, 1699-1915") = True Then
            ElseIf IncomingCitation.Contains("Germany, Saxony, Bautzen, Citizen Rolls, 1496-1923") = True Then
            ElseIf IncomingCitation.Contains("Germany, Saxony, Dresden, Citizens' Documents and Business Licenses, 1820-1962") = True Then
            ElseIf IncomingCitation.Contains("Germany, Saxony, Freiberg, Funeral Sermons, 1614-1661") = True Then
            ElseIf IncomingCitation.Contains("Germany, Saxony, Leipzig, Miscellaneous City Records, 1701-1922") = True Then
            ElseIf IncomingCitation.Contains("Germany, Saxony, Meissen, Miscellaneous City Records, 1724-1889") = True Then
            ElseIf IncomingCitation.Contains("Germany, Saxony-Anhalt, Halberstadt Kreisarchiv, Ahnenpäße (Ancestor Passports)") = True Then
            ElseIf IncomingCitation.Contains("Germany, Saxony-Anhalt, Halberstadt Kreisarchiv, City Directories, Citizen Rolls, Residence Lists, and School Directories, 1700-1933") = True Then
            ElseIf IncomingCitation.Contains("Germany, Schleswig-Holstein, Kreis Steinburg, Civil Registration, 1874-1983") = True Then
            ElseIf IncomingCitation.Contains("Germany, Westfalen, Minden, Index to Funeral Sermons, 1580-1740") = True Then
            ElseIf IncomingCitation.Contains("Germany, Württemberg, Albstadt, Miscellaneous City Records, 1705-1850") = True Then
            ElseIf IncomingCitation.Contains("Germany, Württemberg, Schwäbisch Hall, Probate Records, 1803-1929") = True Then
            End If
        ElseIf IncomingCitation.Contains("Ghana") = True Then
            If IncomingCitation.Contains("Ghana Census, 1984") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Ghana, Accra, Marriages, 1863-2003") = True Then
            End If
        ElseIf IncomingCitation.Contains("Gibraltar") = True Then
            If IncomingCitation.Contains("Gibraltar Births and Baptisms, 1704-1876") = True Then
            ElseIf IncomingCitation.Contains("Gibraltar Marriages, 1879-1918") = True Then
            End If
        ElseIf IncomingCitation.Contains("Great Britain") = True Then
            If IncomingCitation.Contains("Great Britain Deaths and Burials, 1778-1988") = True Then
            ElseIf IncomingCitation.Contains("Great Britain Marriages, 1797-1988") = True Then
            ElseIf IncomingCitation.Contains("Great Britain, Births and Baptisms, 1571-1977") = True Then
            ElseIf IncomingCitation.Contains("Great Britain, War Office Registers, 1772-1935") = True Then
            End If
        ElseIf IncomingCitation.Contains("Grenada Births and Baptisms, 1866-1891") = True Then
        ElseIf IncomingCitation.Contains("Guam") = True Then
            If IncomingCitation.Contains("Guam Judicial, Land, Obituaries, and Census Records, 1712-2000") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Guam Land Records, 1898-1964") = True Then
            ElseIf IncomingCitation.Contains("Guam, Passenger and Crew Lists, 1947-1952") = True Then
            End If
        ElseIf IncomingCitation.Contains("Guatemala") = True Then
            If IncomingCitation.Contains("Guatemala Baptisms, 1730-1917") = True Then
            ElseIf IncomingCitation.Contains("Guatemala Civil Registration, 1877-2008") = True Then
            ElseIf IncomingCitation.Contains("Guatemala Deaths, 1760-1880") = True Then
            ElseIf IncomingCitation.Contains("Guatemala Marriages, 1750-1930") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Alta Verapaz, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Baja Verapaz, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Catholic Church Records, 1581-1977") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Chimaltenango, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Ciudad de Guatemala, Census, 1877") = True Then
                m_strEventType = "Census"
                m_bIsCensus = True
            ElseIf IncomingCitation.Contains("Guatemala, El Progreso, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Escuintla, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Guatemala, Civil Registration, 1877-2006") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Huehuetenango, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Izabal, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Jalapa, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Jutiapa, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Petén, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Quetzaltenango, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Quiché, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Retalhuleu, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Sacatepéquez, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, San Marcos, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Santa Rosa, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Sololá, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Suchitepéquez, Civil Registration, 1877-1994") = True Then
            ElseIf IncomingCitation.Contains("Guatemala, Zacapa, Civil Registration, 1877-1994") = True Then
            End If
        ElseIf IncomingCitation.Contains("Haiti, Port-au-Prince, Civil Registration, 1794-2012") = True Then
        ElseIf IncomingCitation.Contains("Hawaii") = True Then
            If IncomingCitation.Contains("Hawaii Births and Christenings, 1852-1933") = True Then
            ElseIf IncomingCitation.Contains("Hawaii Deaths and Burials, 1862-1919") = True Then
            ElseIf IncomingCitation.Contains("Hawaii Marriages, 1826-1922") = True Then
            ElseIf IncomingCitation.Contains("Hawaii Obituaries Index, ca. 1980-present") = True Then
            ElseIf IncomingCitation.Contains("Hawaii, Honolulu Index to Passengers, Not Including Filipinos, 1900-1952") = True Then
            ElseIf IncomingCitation.Contains("Hawaii, Honolulu Passenger Lists, 1900-1953") = True Then
            ElseIf IncomingCitation.Contains("Hawaii, Index to Filipino Arrivals to Honolulu, 1946") = True Then
            ElseIf IncomingCitation.Contains("Hawaii, Index to Filipino Passengers Arriving at Honolulu, 1900-1952") = True Then
            ElseIf IncomingCitation.Contains("Hawaii, Marriages, 1826-1954") = True Then
            ElseIf IncomingCitation.Contains("Hawaii, Passenger Lists of Airplanes departing Honolulu, 1942-1948") = True Then
            End If
        End If
        Return bSuccess
    End Function
End Class
